name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: select terraform action
        options:
          - apply
        required: true
      chosen_runner:
        description: 'Select the runner'
        required: true
        default: 'ubuntu-latest'
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      api_host:
        description: 'Enter the API host'
        required: true
      username:
        description: 'Enter username for API authentication'
        required: true
      api_key:
        description: 'Enter API key for API authentication'
        required: true
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ${{ github.event.inputs.chosen_runner }}
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.3
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
        args: '-var="instance_type=t3.micro"'

    - name: Terraform apply
      if: ${{ github.event.inputs.terraform_action == 'apply' }}
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.3
        tf_actions_subcommand: ${{ github.event.inputs.terraform_action }}
        tf_actions_working_dir: '.'
        tf_actions_comment: true
        args: '-auto-approve -var="instance_type=t2.micro"'

    - name: Call API
      run: |
        curl -X GET "${{ github.event.inputs.api_host }}/ecam/dataingestion/ingestion/v1/data/health" \
          -H "Content-Type: application/json" \
          -H "Username: ${{ github.event.inputs.username }}" \
          -H "Apikey: ${{ github.event.inputs.api_key }}"
